name: Blob storage website CI

on:
    push:
        branches: [ main ]
        
permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
           client-id: 924ad864-a538-48d4-9d8e-f04952f52f0c
           tenant-id: e562f78c-d375-479f-9e61-6c663bca9b46
           subscription-id: 1db9c769-08c3-4b8e-9e1c-9aac43aefe4f

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: npm install
    - name: Build
      run: npm run build
    - name: Start
      run: nohup npm start &
    - uses: google-github-actions/setup-gcloud@main
      with:
        version: '276.0.0'
        service_account_email: "git-deploy@primeval-sweep-238715.iam.gserviceaccount.com"
        service_account_key: ${{ secrets.GCPDEPLOY }}
        export_default_credentials: true
    - name:  Deploy static site to google storage
      run: gsutil -m rsync -d -c -r ./ gs://www.spacemoon.com
